### ISSUE TITLE
AbstractAttribute<T> could be parameterized  with T as a Enum?

### ISSUE THREAD

**Issue by fmcarvalho** [lcduarte/XsdToJavaAPI#10]
Instead of using `String` to parametrize `T` and since the restrictions enumerate all possible values, example:

```java
        var1.add("Alternate");
        var1.add("Appendix");
        var1.add("Bookmark");
        ...
```
is it possible to create a Enum type with these values (i.e. Alternate, Appendix, Bookmark, ...) ???

**Comment by lcduarte** [comment]
Done at:

https://github.com/lcduarte/XsdToJavaAPI/commit/262ce394bdb519616d9242ef4fd236b93f577d87
