### ISSUE TITLE
Just one accept method in IElement instead of acceptInit() and acceptEnd()

### ISSUE THREAD

**Issue by fmcarvalho** [lcduarte/XsdToJavaAPI#14]
`IElement` should have only one method `accept()` which initializes the `initVisit`, tracks all child elements visiting each one, and finishes the main visit `endVisit`.

```java
public void accept(Visitor vis) {
    vis.initVisit(this);
    getChildren().forEach(child -> child.accept(vis));
    vis.endVisit(this);
}
```

**Comment by lcduarte** [comment]
Added at:

https://github.com/lcduarte/XsdToJavaAPI/commit/d3504acdb0b8ee58ff98eb716a8c09f5cae16256
