### ISSUE TITLE
Generated Div.class missing FlowContent interface implementation

### ISSUE THREAD

**Issue by fmcarvalho** [lcduarte/XsdToJavaAPI#2]
The `div` element has a `type` attribute, which refers another element (e.g. `<xsd:element name="div" type="simpleFlowContentElement" />`) that should be implemented by the concrete final class, i.e. `div.class`

Maybe, the corresponding field `type` in `XsdElement` should be assigned with an`XsdUnresolved` object, that later will be replaced with a concrete instance of `XsdElement`. So the field `type` should be of a base class of both `XsdUnresolved` and `XsdElement`, instead of just a `String`.

**Comment by lcduarte** [comment]
Changed XsdElement objects type attribute to be of the new type, ReferenceBase. After parsing a XsdElement with a value in its type attribute a UnsolvedElement object its created and will be resolved, if possible, with its ConcreteElement while resolving reference issues.

Changes were also made in the XsdClassGenerator to support extracting interfaces from the XsdElement type attribute.
