### ISSUE TITLE
Add a getName() to IAttribute

### ISSUE THREAD

**Issue by fmcarvalho** [lcduarte/XsdToJavaAPI#25]
Add a getName() to IAttribute

**Comment by lcduarte** [comment]
Done at:

https://github.com/lcduarte/XsdToJavaAPI/commit/c05321f5d09ace28bead2357865804b356b82197

**Comment by fmcarvalho** [comment]
It is only on AbstractAttribute. Why not on IAttribute too?

How can I create a new Attribute with name tutu and value toto?

I cannot extend AbstractAttribute because it has no default constructor and the existing one has package accessibility. So I cannot call any base constructor on a derived class.

**Comment by lcduarte** [comment]
Done at:

https://github.com/lcduarte/XsdToJavaAPI/commit/4428acfbb4980467a6fa8eed1b69b09edd4a7b3e

A new attribute can be added as follow:

```java
Html root = new Html();
root.addAttr(new Attribute<>("toto", "tutu"));
```

**Comment by fmcarvalho** [comment]
Tested
