### ISSUE TITLE
Support binders to all elements

### ISSUE THREAD

**Issue by fmcarvalho** [lcduarte/XsdToJavaAPI#27]
We may want to add a binder to a given element such as:

```java
table.binder((table, list) -> list.forEach(task -> table.tr().td().text(task::getTitle)...etc..)
```

`binder` receives a `Consumer<IElement, Model>`

Then the visitor should be able to do: 

```java
public <U extends IElement> void initVisit(IElement<U> elem) {
        out.print(getElementValue(elem));
        if(elem.isBound()) {
            IElement clone = elem.clone();
            
            clone.bindTo(model) // calls the Consumer<IElement, Model> which MODIFIES the clone
            clone.accept(this);
            // <=> clone.bindTo(model).accept(this);
        }
        // The following task is made by each composite element
        // elem.getChildren().forEach(child -> child.accept(this));
    }
```

**Comment by lcduarte** [comment]
Added a similar solution at:

https://github.com/lcduarte/XsdToJavaAPI/commit/632397cce74b1c691a206ae90fd249ac3e02aa6b

Instead of receiving a model as parameter the Consumer function captures the variables needed in its execution like shown in the following code example:

```java
List<String> tdValues = new ArrayList<>();

tdValues.add("val1");
tdValues.add("val2");
tdValues.add("val3");

table.binder(elem ->
      tdValues.forEach(tdValue ->
          elem.tr().td().text(tdValue)
      )
);
```

This results in the following code in the CustomVisitor initVisit method:

```java
@Override
public <T extends IElement> void initVisit(IElement<T> element) {
    printStream.printf("<%s>\n", element.getName());

    if(element.isBound()) {
        IElement<T> clone = element.cloneElem();

        clone.binderApply(); // calls the Consumer<IElement, Model> which MODIFIES the clone

        clone.getChildren().forEach((IElement child) ->
            child.accept(this)
        );
    }
}
```

**Comment by fmcarvalho** [comment]
I am not sure this is a good option. A tree of `xmlet.htmlapi.IElement` objects (template) should be used with used with different Model instances. 

If the binder captures the model (i.e. `tdValues` form the example above) then we cannot reuse the same template with a different Model instance. Am I right?

How can I bind the `table` (from the example above) to a different instance than `tdValues`?

**Comment by lcduarte** [comment]
This was the only way I could implement this feature without bringing problems to the remaining API. 

I tried to implement the `BiConsumer<IElement, M>`, which would allow `binder(BiConsumer<IElement, M> binderFunction)` and the `bindTo(M model)`. But to do this I had to add a new type parameter to `AbstractElement` and therefore to all the Elements. This brought me problems I didn't figured out how to solve (the self method wouldn't return concrete types such as `Html`, `Div`, etc, only raw `IElements`). If there's a way to solve this problem I agree that this solution is much better than the present one.

Answering the questions, in order to bind a different model instance we have to call the binder method again, or, in this case the model being a list it is possible to clear the list, add new values and generate the table with new values. I implemented a test with the multiple usages in the method `testBinderUsage` following class:

https://github.com/lcduarte/XsdToJavaAPI/blob/Development/XsdToJavaAPIRoot/HtmlApiTest/src/test/java/HtmlApiTest.java

**Comment by fmcarvalho** [comment]
Make `binder()` with a generic parameter such as: `<M> T binder(BiConsumer<T, M> binderFunction)`, instead of using `M` in type `IElement`.

Then erase the type parameter `M` and store the `binderFunction` just as `BiConsumer<?, ?>` or `BiConsumer`... I am not sure what is better.

The method `bindTo(Object model)` receives a model without a strong type. In this way it is explicit that there is no compile time verification between the model instance and the binder function. 

This is the better approach with minimum complexity.

**Comment by lcduarte** [comment]
Corrected at:

https://github.com/lcduarte/XsdToJavaAPI/commit/d55b999c7ea5cbf676e4aab23a892d174d864f48

Also, a new release was made, the new version for htmlApi is 1.0.1

**Comment by fmcarvalho** [comment]
I thought it was done, but it was not. I missed to test binding the same view twice. Since I was not cloning the bound element, then it was duplicating the children. Consider the following use case where `table`  element already has a first row with headings (`th`) and then adds the following binder:

```java
table.<List<Task>>binder((tbl, list) -> {
            list.forEach(task -> {
                tbl.tr()
                        .td().text(task.getTitle()).$()
                        .td().text(task.getDescription()).$()
                        .td().text(task.getPriority().toString());
            });
        });
```
If the visitor does: `elem.bindTo(model)`, then on future visits it will find the children added by the previous visits.

To avoid that the visitor should clone the `elem`. But it CANNOT simply do the following statement because it results in an infinite recursion.:

```java
elem.cloneElem().bindTo(model).accept(this); // where this is an AbstractVisitor implementation 
```

So, the visitor must do something like:

```java
        if(elem.isBound()) {
            List<IElement> children = elem.cloneElem().bindTo(model).getChildren();
            children.forEach(item -> item.accept(this));
        }
```
This is almost fine. The problem is that each element already promotes the visit of its children on the `accept()` method. So the first row of headings will appear twice: at the beginning and at the end of the table.

So I think the better solution is to remove the following from the `accept` method of each element concrete class: 

```java
        this.getChildren().forEach((var1) -> {
            var1.accept(visitor);
        });
```

and let the visitor decide whether to use a clone or the element itself:

```java
        if(elem.isBound()) {
            List<IElement> children = elem.cloneElem().bindTo(model).getChildren();
            children.forEach(item -> item.accept(this));
        } else {
             elem.getChildren().forEach(item -> item.accept(this));
        }
```

With this in mind it seems that we do not need 2 visit methods: `initVisit` and `endVisit`. But I am not totally aware if is this true.

Can we remove children visit from `accept`? Can we merge visit methods in a single visit?

**Comment by lcduarte** [comment]
With this code I don't get duplicated elements:

The visitor implementation:

```java
public <T extends IElement> void initVisit(IElement<T, ?> element) {
    printStream.printf("<%s>\n", element.getName());

    if(element.isBound()) {
        element.cloneElem()
                .bindTo(model)
                .getChildren()
                .forEach( child ->
                    ((IElement) child).accept(this)
                );
    }
}
```

The test method:

```java
public void testBinderUsage(){
    List<String> tdValues1 = new ArrayList<>();
    List<String> tdValues2 = new ArrayList<>();

    tdValues1.add("val1");
    tdValues1.add("val2");
    tdValues1.add("val3");

    tdValues2.add("val4");
    tdValues2.add("val5");
    tdValues2.add("val6");

    Html<Html> root = new Html<>();

    root.body()
            .table()
                .<List<String>>binder((elem, list) ->
                        list.forEach(tdValue ->
                                elem.tr().td().text(tdValue)
                        )
                ).$()
            .div();

    CustomVisitor<List<String>> customVisitor1 = new CustomVisitor<>(tdValues1);

    String expected1 = "<html>\n<body>\n<table>\n" +
                            "<tr>\n<td>\nval1\r\n</td>\n</tr>\n" +
                            "<tr>\n<td>\nval2\r\n</td>\n</tr>\n" +
                            "<tr>\n<td>\nval3\r\n</td>\n</tr>\n" +
                        "</table>\n<div>\n</div>\n</body>\n</html>\n";

    Assert.assertTrue(customVisitPrintAssert(customVisitor1, root, expected1));
    Assert.assertTrue(customVisitPrintAssert(customVisitor1, root, expected1));

    CustomVisitor<List<String>> customVisitor2 = new CustomVisitor<>(tdValues2);

    String expected2 = "<html>\n<body>\n<table>\n" +
                            "<tr>\n<td>\nval4\r\n</td>\n</tr>\n" +
                            "<tr>\n<td>\nval5\r\n</td>\n</tr>\n" +
                            "<tr>\n<td>\nval6\r\n</td>\n</tr>\n" +
                        "</table>\n<div>\n</div>\n</body>\n</html>\n";

    Assert.assertTrue(customVisitPrintAssert(customVisitor2, root, expected2));
}
```

**Comment by fmcarvalho** [comment]
If you insert a tr with headers before the binder (i.e. `<tr><th>Title</th></tr>`) you will see the heading line duplicated at the beginning and at the end of the table:

```java
Table<Body<Html>> table = root.body().table()
table.tr().th().text("Title");
table.<List<String>>binder((elem, list) ->
                        list.forEach(tdValue ->
                                elem.tr().td().text(tdValue)
                        )
                );
```
