### ISSUE TITLE
Is it possible to include an additional U generic type in IElement and make $() return this U?

### ISSUE THREAD

**Issue by fmcarvalho** [lcduarte/XsdToJavaAPI#30]
**NOTE**:  Thinking a little more I think it is not possible to satisfy this issue, because `U` must be resolved in compile time and we want to resolve it at runtime. Nevertheless, I will leave here the description:

It would be useful if each `IElement` has the type of its parent, i.e. `U`, and then this `U` could be used as the return type of `$()`.

For example when you call `div.table()` it would return an instance of `Table` that implements `IElement<Table, Div>` and where `U` is `Div`corresponding to its parent element type. Then, we would not need any more to use `.<Div>$()`  and could simply call `$()`.

**Comment by lcduarte** [comment]
After a few changes I managed to solve most of the problems that happen implementing that requirement, but now I have a problem that I think I can't solve.

```java
    Head<Html> head = root.head();
    Meta<Head> meta = head.meta();
    Head metaParent = meta.$();
    IElement headParent = metaParent.$();
```

As we can see in the code sample the `$()` returns the correct type, but loses the information of the parent. In the example the metaParent should be Head<Html> and not Head, furthermore calling `$()` loses the type completely resulting in a IElement.

**Comment by fmcarvalho** [comment]
I am not figuring out a solution either. Unless with explicit cast: 

```java
Head<Html> metaParent = (Head<Html>) meta.$();
Html headParent = metaParent.$();
```

This works?

I would say that in most cases we just want to go up one level and for them you keep parent type information. But, not for grand parent.  If we need a reference for grand father, then it would be better to keep it first in a auxiliary local variable.

**Comment by lcduarte** [comment]
I've figured out my mistake.

Using the Div class as an example, I had:

`Div<P extends IElement> extends AbstractElement<Div, P> implements IFlowContent<Div, P>`

This solution was erasing the type P of Div when the interface received it, so I solved the problem changing it to:

`Div<P extends IElement> extends AbstractElement<Div<P>, P> implements IFlowContent<Div<P>, P>`

With that change the resulting API works like this (The variables aren't needed, it just serves to show how it works):

```java
Body<Html<Html>> body = root.body();
Div<Body<Html<Html>>> div = body.div();
Img<Div<Body<Html<Html>>>> img = div.img();
Div<Body<Html<Html>>> parent1 = img.$();
Body<Html<Html>> parent2 = parent1.$();
Html<Html> parent3 = parent2.$();
```

**Comment by fmcarvalho** [comment]
This is awesome. I need time to completely mentally realize your solution.
