### ISSUE TITLE
Is it possible to change $() to º() ?

### ISSUE THREAD

**Issue by fmcarvalho** [lcduarte/XsdToJavaAPI#32]
`º()` has the advantage of not being associated with any other language/API like `$()` which is related with jquery.

Moreover we do not need to press two keys (like shift + .... ) to write the `º`.

I think `º` is awesome, it looks like dot and it is also superscript, which we can be interpreted as something above, like the parent element.

**Comment by lcduarte** [comment]
Done at:

https://github.com/lcduarte/XsdToJavaAPI/commit/62e623466d9ff483ef575104d61a26b49a170c79
