### ISSUE TITLE
InteliI cannot disassembly Text class

### ISSUE THREAD

**Issue by fmcarvalho** [lcduarte/XsdToJavaAPI#33]
For `Text` class now it shows `/* compiled code */`. But it works fine for other elements. I think that I have already seen the Text disassembled in a previous release. Can you figure out what is happening now?

![image](https://user-images.githubusercontent.com/578217/36388240-20a150ba-1593-11e8-88c6-695c7d04fe36.png)

**Comment by lcduarte** [comment]
The behavior I was getting was different than the one on the image, I had only a method with the `/* compiled code */` but I solved that problem and now all the code appears to be correct. I'll push a new release and we'll see if that fixes all of it.

Done at:
https://github.com/lcduarte/XsdToJavaAPI/commit/4d7c2ce1f7dd17f5065bd842c7b1f85c29b47403
