### ISSUE TITLE
For next year

### ISSUE THREAD

**Issue by fmcarvalho** [lcduarte/XsdToJavaAPI#34]
Do not look at this now....

For performance purposes we could imagine an alternative approach where the methods of the fluent API (i.e. `div(), `p()`, `img()`, etc) immediately call the visitor to produce the output, instead of storing elements in a internal data structure.

In this case the call to `$()`  or `º()` would be responsible to end the visit for the given element.

**Comment by lcduarte** [comment]
Done in [XsdAsmFaster](https://github.com/xmlet/XsdAsmFaster).
