### ISSUE TITLE
Text unsupported methods should throw IllegaleOperationException

### ISSUE THREAD

**Issue by fmcarvalho** [lcduarte/XsdToJavaAPI#35]
Do not return null on `addAttr(IAttribute var1)` and `addChild(IElement var1)`. 

Throw IllegaleOperationException instead.

**Comment by lcduarte** [comment]
Done at:

https://github.com/lcduarte/XsdToJavaAPI/commit/74205b400b24fbf63250c4ac8ff134d888f8661f

Also, the new version (1.0.4) of htmlapi is available now.
