### ISSUE TITLE
Naming conventions, namely on packages must be on lower case and begin with  org.xmlet

### ISSUE THREAD

**Issue by fmcarvalho** [lcduarte/XsdToJavaAPI#36]
All packages in all modules/projects must begin with with  `org.xmlet`.

For example the `Visitor` interface should be in a package as: `com.xmlet.htmlapi.Visitor`

In the meanwhile maybe the `Visitor` should be renamed to `ElementVisitor` denoting something related with HtmlApi.

**Comment by lcduarte** [comment]
I suppose that the `com` in `com.xmlet.htmlapi.Visitor` was meant to be `org`. If that is the case the change is made at:

https://github.com/lcduarte/XsdToJavaAPI/commit/f43c5438410068abafee04ee9f3e5e829fb6d1ff

If it was really meant to be `com` instead of `org` I'll change it in a next commit.

**Comment by fmcarvalho** [comment]
You are right. I meant org and not com
