### ISSUE TITLE
Naming conventions, remove I prefix from interfaces name

### ISSUE THREAD

**Issue by fmcarvalho** [lcduarte/XsdToJavaAPI#37]
Remove I prefix from interfaces name. That is a .net convention not followed in Java.

**Comment by lcduarte** [comment]
Removed at:

https://github.com/lcduarte/XsdToJavaAPI/commit/f43c5438410068abafee04ee9f3e5e829fb6d1ff

**Comment by fmcarvalho** [comment]
Now what is the name of the former class `Attribute`? Did you remove it?

**Comment by fmcarvalho** [comment]
I think I found it. Is it `BaseAttribute`?
