### ISSUE TITLE
TextNode are not defined in Xsd, but should be supported in generated Java API

### ISSUE THREAD

**Issue by fmcarvalho** [lcduarte/XsdToJavaAPI#4]
Instances of concrete elements in the generated API, such as p, h1, div, etc... should provide some way of adding text nodes.

Examples:
    div
        .text("Title:  ISEL MPD project")
        .br()
        .text("A Java library for serializing objects in HTML.")

**Comment by fmcarvalho** [comment]
We already support text nodes, but is still missing a fluent API like a `.text(...)` method.

**Comment by lcduarte** [comment]
Added at:

537143644efd4caa0ff7dbd6ddca346b938e0c60
