### ISSUE TITLE
Reorganize projects (modules) 

### ISSUE THREAD

**Issue by fmcarvalho** [lcduarte/XsdToJavaAPI#7]
Divide in 3 main projects:
* JavaXsdParser
* Xsd2JavaApi
* Html5Xsd2JavaApi

The build process of last project Html5Xsd2JavaApi should run the Xsd2JavaApi to create a jar with the generated classes for the Html5.xsd. 

Basically this Html5Xsd2JavaApi just has a main resource Html5.xsd and a build dependency to the Xsd2JavaApi, which should be included in the Maven build process.

Finally, the Html5Xsd2JavaApi  does not has tests. Those tests should be in a separated project (module) Html5Xsd2JavaApiTest that refers the former. So, whenever we build Html5Xsd2JavaApiTest it will requires that Html5Xsd2JavaApi   be up to date and if not, forces its build to run and to generate a new JAR.

Example of a multi-module project with maven https://github.com/AsyncHttpClient/async-http-client

**Comment by lcduarte** [comment]
Done at:

5e0b38a1ac076c5005a4a889eec8d1fe62af6d21
