### ISSUE TITLE
Remove dependency on pom.xml  of Html5Xsd2JavaApi from absolute path to XSD source file

### ISSUE THREAD

**Issue by fmcarvalho** [lcduarte/XsdToJavaAPI#8]
The pom.xml of project Html5Xsd2JavaApi contains a reference to the absolute path of the XSD file that is passed by argument to XsdClassGeneratorMain class.

Remove the absolute path, some how.

**Comment by lcduarte** [comment]
Done at:
https://github.com/lcduarte/XsdToJavaAPI/commit/f0aac2cd88f0a3c4baed02e3c91382614a147be6
